services:
  app:
    build: .
    image: maniaque/pytime
    ports:
      - "8080:80"
    environment:
      PYTHONPYCACHEPREFIX: /tmp
  
  tests:
    build: .
    image: maniaque/pytime
    command: pytest
    environment:
      PYTHONPYCACHEPREFIX: /tmp
    profiles: [ "tests" ]
