---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytime
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: pytime
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
...
