---
apiVersion: v1
kind: Service
metadata:
  name: pytime-service
spec:
  type: NodePort
  selector:
    app: pytime
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30003
...
